routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Client'], function () {
    Route::get('/', 'HomeController@index');

    Route::get('/get-more-posts', 'HomeController@getMorePosts');

    Route::get('/show-post/{id}', 'HomeController@showPost');

    Route::post('/add-comment/{post_id}', 'CommentController@addComment');
});

Route::resource('post', 'PostController');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $table = 'comments';
    protected $primaryKey = 'comment_id';
    protected $fillable = [
        'post_id',
        'comment_user_name',
        'comment_text'
    ];

    /**
     * Return post comments
     *
     * @param $post_id
     * @return mixed
     */
    protected function getPostComment($post_id)
    {
        return $this
            ->where('post_id', $post_id)
            ->orderBy('created_at', 'desc')
            ->get();
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';
    protected $primaryKey = 'post_id';
    protected $fillable = [
        'post_title',
        'post_image',
        'post_text'
    ];

    /**
     * Create new post
     *
     * @param $post_data
     * @return mixed
     */
    protected function addNewPost($post_data)
    {
        return $this->create([
            'post_title' => $post_data['post_title'],
            'post_image' => $post_data['post_image'],
            'post_text' => $post_data['post_text']
        ]);
    }

    /**
     * Return list posts
     *
     * @return mixed
     */
    protected function getAllPost()
    {
        return $this->orderBy('created_at', 'desc')->paginate(10);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Client/CommentController.php
<?php

namespace App\Http\Controllers\Client;

use App\Comment;
use App\Http\Requests\CommentRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    /**
     * Add new comment to post
     *
     * @param CommentRequest $request
     * @param $post_id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function addComment(CommentRequest $request, $post_id)
    {
        $data = [
            'comment_user_name' =>'Гість',
            'post_id' => $post_id,
            'comment_text' => $request->get('comment_text')
        ];

        Comment::create($data);

        return redirect()->back()->with('message', 'Коментар успішно доданий');
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public $data = [];

    /**
     * Show index page (posts)
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->data['posts'] = Post::getAllPost();
        $this->data['page'] = [
            'title' => 'Blog',
            'image' => asset('/img/home-bg.jpg')
        ];

        return view('client.pages.index', $this->data);
    }

    public function getMorePosts()
    {
        $count = request('count');
        $limit = request('limit');

        $posts = Post::orderBy('created_at', 'desc')
            ->offset($count)
            ->limit($limit)
            ->get();

        return response()->json(['posts' => $posts]);
    }

    /**
     * Show one post
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showPost($id)
    {
        $this->data['post'] = Post::find($id);

        $this->data['comments'] = Comment::getPostComment($id);

        $this->data['page'] = [
            'title' => $this->data['post']['post_title'],
            'image' => asset('/uploads/'.$this->data['post']['post_image'])
        ];

        return view('client.pages.post', $this->data);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected $data = [];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['posts'] = [];

        return view('admin.pages.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['page_title'] = 'Новий пост';

        return view('admin.pages.post_create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PostRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(PostRequest $request)
    {
        $image = $request->file('post')['image'];

        $imageName = $image->getClientOriginalName();

        $image->move(
            public_path('uploads/'), $imageName
        );

        $data = [
            'post_title' => $request->get('post')['title'],
            'post_text' => $request->get('post')['text'],
            'post_image' => $imageName
        ];

        // create news post
        Post::addNewPost($data);

        return response()->json(['created' => 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <!-- styles -->
    <link href="{{ asset('/css/admin_styles.css') }}" rel="stylesheet">

    <!-- include summernote css/js-->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<!-- Page Header -->
@include('admin.layouts.header')
<!-- / Page Header -->

{{-- Page content --}}
@yield('content')
{{-- / Page content --}}

<!-- Footer -->
@include('admin.layouts.footer')
<!-- / Footer -->

<!-- jQuery -->
<script src="{{ asset('/vendor/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('/vendor/bootstrap/js/bootstrap.min.js') }}"></script>

<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>

<script src="{{ asset('/js/custom.js') }}"></script>

@stack('script')
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer>
    <div class="container">

        <div class="copy text-center">
            Copyright 2014 <a href='#'>Website</a>
        </div>

    </div>
</footer>

resources/views/admin/layouts/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="index.html">Bootstrap Admin Theme</a></h1>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
	                         <button class="btn btn-primary" type="button">Search</button>
	                       </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="login.html">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/pages/index.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- Page content -->
<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="{{ route('post.index') }}"><i class="glyphicon glyphicon-paperclip"></i> Posts</a></li>
                    <li class="current"><a href="{{ route('post.create') }}"><i class="glyphicon glyphicon-pencil"></i> New Posts</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-10">
            <div class="content-box-large">
                <table class="table table-hover">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    @foreach($posts as $item)
                        <tr>
                            <td>{{ $item->post_id }}</td>
                            <td>{{ $item->name }}</td>
                            <td>
                                <button class="btn btn-danger btn-xs"
                                        onclick="if(confirm('Deleted?')){sendForm('#post-{{ $item->language_id }}');}">
                                    <i class="fa fa-trash"></i></button>
                                <a href="{{ url('/admin/post/'.$item->language_id) }}"
                                   class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>

                                <form action="{{ route('post.destroy', $item->language_id) }}" id="post-{{ $item->language_id }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</div>
<!-- / Page content -->
@endsection

resources/views/admin/pages/post_create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Page content -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-2">
                <div class="sidebar content-box" style="display: block;">
                    <ul class="nav">
                        <!-- Main menu -->
                        <li class="current"><a href="{{ url('/admin/post') }}"><i
                                        class="glyphicon glyphicon-pencil"></i> Posts</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10">
                <div class="content-box-large">

                    <div class="content-box-large">
                        <div class="panel-heading">
                            <div class="panel-title">{{ $page_title }}</div>
                        </div>

                        <div class="panel-body">
                            <form data-new-post-form>
                                {{ csrf_field() }}
                                <fieldset>
                                    <div class="col-sm-8 form-group" data-post="image">
                                        <label class="control-label">Картинка</label>
                                        <div>
                                            <input type="file" class="btn btn-default" name="post[image]">
                                            <p class="help-block">
                                                File types: jpg, jpeg, gif, png. Max file size 2Mb
                                            </p>
                                        </div>
                                    </div>

                                    <div class="col-sm-4">
                                        <img id="img-preview" src="" alt="" style="max-width: 150px; height: auto;">
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <div class="form-group" data-post="title">
                                        <label>Назва</label>
                                        <input class="form-control" placeholder="Назва поста" type="text"
                                               name="post[title]">
                                    </div>

                                    <div class="form-group" data-post="text">
                                        <label>Контент</label>
                                        <textarea name="post[text]" data-post-text></textarea>
                                    </div>
                                </fieldset>

                                <div id="liqpay_checkout"></div>

                                <div data-save-button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')


<script>
    window.LiqPayCheckoutCallback = function() {
        LiqPayCheckout.init({
            data: "eyJ2ZXJzaW9uIjozLCJhY3Rpb24iOiJwYXkiLCJwdWJsaWNfa2V5IjoiaTU5NjIwODQ4MzI3IiwiYW1vdW50IjoiMTAiLCJjdXJyZW5jeSI6IlVBSCIsImRlc2NyaXB0aW9uIjoicG9zdGVkIiwidHlwZSI6ImJ1eSIsInNhbmRib3giOiIxIiwibGFuZ3VhZ2UiOiJydSJ9",
            signature: "2C2f52effx6vOxOV80Mx5drhk4o=",
            embedTo: "#liqpay_checkout",
            mode: "embed"
        }).on("liqpay.callback", function(data){
            if (data.result == 'success') {
                post.save();
            }
        }).on("liqpay.ready", function(data){
            // ready
        }).on("liqpay.close", function(data){
            // close
        });
    };
</script>
<script src="//static.liqpay.com/libjs/checkout.js" async></script>

<script>
    $(document).ready(function () {
        $('textarea[data-post-text]').summernote({
            height: 300
        });
    });

    $("input[name=\'post[image]\']").change(function () {
        readURL(this);
    });

    /*----------------------------------------------------------------------------*/
    /* Preview image
     /*----------------------------------------------------------------------------*/
    function readURL(input) {

        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.readAsDataURL(input.files[0]);

            reader.onload = function (e) {
                $('img#img-preview').attr('src', e.target.result);
            };
        }
    }

    /*----------------------------------------------------------------------------*/
    /* Send form and upload image
     /*----------------------------------------------------------------------------*/
    var post = {
        'save': function () {

            var request = new XMLHttpRequest();
            request.open("POST", "{{ route('post.store') }}");
            request.send(new FormData(document.querySelector("form[data-new-post-form]")));

            request.onload = function () {

                if (request.status == 200) {

                    $('div[data-post]').css({'border': 'none'});

                    alert('Пост додано');

                    return window.location.href = '{{ url('/') }}';
                }

                if (request.status == 422) {

                    var errors = false;

                    if (request.responseText) {
                        errors = JSON.parse(request.responseText);
                    }

                    if (errors) {
                        $('div[data-post]').css({'border': 'none'});

                        if (errors['post.image']) {
                            $('div[data-post=\'image\']').css({'border': '1px solid #c00'});
                        }
                        if (errors['post.title']) {
                            $('div[data-post=\'title\']').css({'border': '1px solid #c00'});
                        }
                        if (errors['post.text']) {
                            $('div[data-post=\'text\']').css({'border': '1px solid #c00'});
                        }

                        return alert('Помилка валідації');
                    }
                }
            };
        }
    }
</script>
@endpush

resources/views/client/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{{ asset('/css/clean-blog.min.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ asset('/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    @include('client.layouts.nav_bar')
    <!-- / Navigation -->

    <!-- Page Header -->
    @include('client.layouts.header')
    <!-- / Page Header -->

    {{-- Page content --}}
    @yield('content')
    {{-- / Page content --}}

    <hr>
    <!-- Footer -->
    @include('client.layouts.footer')
    <!-- / Footer -->

<!-- jQuery -->
<script src="{{ asset('/vendor/jquery/jquery.min.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('/vendor/bootstrap/js/bootstrap.min.js') }}"></script>

<!-- Contact Form JavaScript -->
<script src="{{ asset('/js/jqBootstrapValidation.js') }}"></script>
<script src="{{ asset('/js/contact_me.js') }}"></script>

<!-- Theme JavaScript -->
<script src="{{ asset('/js/clean-blog.min.js') }}"></script>

@stack('script')

</body>
</html>

resources/views/client/layouts/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            </div>
        </div>
    </div>
</footer>

resources/views/client/layouts/header.blade.php
<header class="intro-header" style="background-image: url('{{ $page['image'] }}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>{{ $page['title'] }}</h1>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/client/layouts/nav_bar.blade.php
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a href="about.html">About</a>
                </li>
                <li>
                    <a href="post.html">Sample Post</a>
                </li>
                <li>
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

resources/views/client/pages/index.blade.php
@extends('client.layouts.app')

@section('content')
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                <div data-blog-posts>
                @foreach($posts as $post)
                <div class="post-preview">
                    <a href="{{ url('/show-post/'.$post->post_id) }}">
                        <h2 class="post-title">
                            {{ $post->post_title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ str_limit(strip_tags($post->post_text), 25, '...') }}
                        </h3>
                    </a>
                    <p class="post-meta">Posted on {{ $post->created_at }}</p>
                </div>
                <hr>
                @endforeach
                </div>

                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="javascript:void(0);" onclick="loadPost();">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- / Main Content -->
@endsection

@push('script')
<script>
    var count = 5;
    var limit = 2;
    var load = false;

    $(document).ready(function() {
        $(window).scroll(function() {
            loadPost();
        });
    });

    function loadPost() {
        if (!load && ($(window).scrollTop() + $(window).height() >= $(document).height()-300)) {

            $.ajax({
                url: "{{ url('/get-more-posts') }}",
                method: 'GET',
                data: {"count": count, "limit": limit},
                beforeSend: function () {
                    load = true;
                }
            }).done(function(response) {

                var basePostURL = "{{ url('/show-post/') }}";

                if (response.posts) {

                    $.each(response.posts, function(index, post) {

                        var description = post['post_text'];
                        if(description.length > 25) description = description.substring(0,25) + '...';

                        $('div[data-blog-posts]').append(
                            '<div class="post-preview">' +
                            '<a href="' + basePostURL + '/' + post['post_id'] + '">' +
                            '<h2 class="post-title">'+
                            post['post_title'] +
                            '</h2>' +
                            '<h3 class="post-subtitle">'+
                            description +
                            '</h3>' +
                            '</a>' +
                            '<p class="post-meta">Posted on ' + post['created_at'] + '</p>' +
                            '</div>' +
                            '<hr>'
                        );
                    });

                    load = false;
                    count += 10;
                }
            });
        }
    }
</script>
@endpush

resources/views/client/pages/post.blade.php
@extends('client.layouts.app')

@section('content')
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                    {!! $post['post_text'] !!}

                </div>
            </div>

            <div class="row">
                <form action="{{ url('/add-comment/' . $post['post_id']) }}" method="post">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label>Comment</label>
                        <textarea name="comment_text" class="form-control"></textarea>
                    </div>

                    <div class="btn-group">
                        <button type="submit" class="btn btn-success">Add Comment</button>
                    </div>
                </form>

                <hr/>

                @foreach($comments as $comment)
                    <div class="row">
                        <div class="col-md-12 panel-warning">
                            <div class="content-box-header panel-heading">
                                <div class="text-info">{{ $comment->comment_user_name }}</div>
                                <i>{{ $comment->created_at }}</i>
                            </div>
                            <div class="content-box-large box-with-header">
                                {{ $comment->comment_text }}
                                <br /><br />
                            </div>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </article>
    <!-- / Post Content -->

    </form>
@endsection